title: Brian (Jeong Gyu) Lee
logo: /assets/headshot_circle.jpeg

description: >
  <a href="/me/assets/lee_CV_F26.pdf">Download my CV</a><br>
  <a href="YOUR_GOOGLE_DRIVE_LINK">View my portfolio</a>

show_downloads: false
theme: jekyll-theme-minimal
